### ISSUE TITLE
handle all possible fails and restart untill last action will not be success

### ISSUE THREAD

**Issue by vskaiman** [vsevolodk/birthday.bot#14]
```
2017-09-04 09:18:17 ERROR SkypeHolder:32 - Skype login failed, application wil be shutdown
com.samczsun.skype4j.exceptions.ConnectionException
        at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:110)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:397)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:319)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:299)
        at com.samczsun.skype4j.internal.client.FullClient.login(FullClient.java:70)
        at com.birthday.bot.skype.holder.SkypeHolder.reBuildSkype(SkypeHolder.java:29)
        at com.birthday.bot.skype.Reloader.reload(Reloader.java:11)
        at com.birthday.bot.skype.bot.job.SkypeReloader.execute(SkypeReloader.java:20)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketException: Socket is not connected: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
```

**Comment by vskaiman** [comment]
```
2017-09-06 01:19:31 ERROR Subscriber:26 - Skype subscribing for listener is failed
com.samczsun.skype4j.exceptions.ConnectionException
        at com.samczsun.skype4j.internal.ExceptionHandler.generateException(ExceptionHandler.java:110)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:397)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:319)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.post(Endpoints.java:303)
        at com.samczsun.skype4j.internal.SkypeImpl.subscribe(SkypeImpl.java:467)
        at com.birthday.bot.skype.bot.listener.Subscriber.subscribe(Subscriber.java:24)
        at com.birthday.bot.skype.bot.listener.Subscriber.process(Subscriber.java:18)
        at com.birthday.bot.skype.Reloader.reload(Reloader.java:12)
        at com.birthday.bot.skype.bot.job.SkypeReloader.execute(SkypeReloader.java:20)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
        at com.samczsun.skype4j.internal.Endpoints$EndpointConnection.connect(Endpoints.java:371)
        ... 9 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(Unknown Source)
        ... 19 more
```
